export const ADD_AVENGER = 'ADD_AVENGER';
export const SELECTED_AVENGER = 'SELECTED_AVENGER';
export const CLOSE_SELECTED_AVENGER = 'CLOSE_SELECTED_AVENGER';
export const LIKED_AVENGER = 'LIKED_AVENGER';
export const SEARCH_AVENGER = 'SEARCH_AVENGER';
export const RATED_AVENGER = 'RATED_AVENGER';
